/*
-----------------------------------------------------------------------------
This source file is part of Terminal_G33k
Copyright (c) 2005 The Terminal_G33k Team
Also see acknowledgements in Readme.txt

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License version 2.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
or go to http://www.gnu.org/copyleft/gpl.txt
-----------------------------------------------------------------------------
*/
#ifndef TGGL_LINKED_H
#define TGGL_LINKED_H

//GLU
#define tggluBuild2DMipmaps gluBuild2DMipmaps
#define tggluBuild1DMipmaps gluBuild1DMipmaps
#define tggluErrorString gluErrorString

//GL
#define tgglAccum glAccum
#define tgglAlphaFunc glAlphaFunc
#define tgglAreTexturesResident glAreTexturesResident
#define tgglArrayElement glArrayElement
#define tgglBegin glBegin
#define tgglBindTexture glBindTexture
#define tgglBitmap glBitmap
#define tgglBlendFunc glBlendFunc
#define tgglCallList glCallList
#define tgglCallLists glCallLists
#define tgglClear glClear
#define tgglClearAccum glClearAccum
#define tgglClearColor glClearColor
#define tgglClearDepth glClearDepth
#define tgglClearIndex glClearIndex
#define tgglClearStencil glClearStencil
#define tgglClipPlane glClipPlane
#define tgglColor3b glColor3b
#define tgglColor3bv glColor3bv
#define tgglColor3d glColor3d
#define tgglColor3dv glColor3dv
#define tgglColor3f glColor3f
#define tgglColor3fv glColor3fv
#define tgglColor3i glColor3i
#define tgglColor3iv glColor3iv
#define tgglColor3s glColor3s
#define tgglColor3sv glColor3sv
#define tgglColor3ub glColor3ub
#define tgglColor3ubv glColor3ubv
#define tgglColor3ui glColor3ui
#define tgglColor3uiv glColor3uiv
#define tgglColor3us glColor3us
#define tgglColor3usv glColor3usv
#define tgglColor4b glColor4b
#define tgglColor4bv glColor4bv
#define tgglColor4d glColor4d
#define tgglColor4dv glColor4dv
#define tgglColor4f glColor4f
#define tgglColor4fv glColor4fv
#define tgglColor4i glColor4i
#define tgglColor4iv glColor4iv
#define tgglColor4s glColor4s
#define tgglColor4sv glColor4sv
#define tgglColor4ub glColor4ub
#define tgglColor4ubv glColor4ubv
#define tgglColor4ui glColor4ui
#define tgglColor4uiv glColor4uiv
#define tgglColor4us glColor4us
#define tgglColor4usv glColor4usv
#define tgglColorMask glColorMask
#define tgglColorMaterial glColorMaterial
#define tgglColorPointer glColorPointer
#define tgglCopyPixels glCopyPixels
#define tgglCopyTexImage1D glCopyTexImage1D
#define tgglCopyTexImage2D glCopyTexImage2D
#define tgglCopyTexSubImage1D glCopyTexSubImage1D
#define tgglCopyTexSubImage2D glCopyTexSubImage2D
#define tgglCullFace glCullFace
#define tgglDeleteLists glDeleteLists
#define tgglDeleteTextures glDeleteTextures
#define tgglDepthFunc glDepthFunc
#define tgglDepthMask glDepthMask
#define tgglDepthRange glDepthRange
#define tgglDisable glDisable
#define tgglDisableClientState glDisableClientState
#define tgglDrawArrays glDrawArrays
#define tgglDrawBuffer glDrawBuffer
#define tgglDrawElements glDrawElements
#define tgglDrawPixels glDrawPixels
#define tgglEdgeFlag glEdgeFlag
#define tgglEdgeFlagPointer glEdgeFlagPointer
#define tgglEdgeFlagv glEdgeFlagv
#define tgglEnable glEnable
#define tgglEnableClientState glEnableClientState
#define tgglEnd glEnd
#define tgglEndList glEndList
#define tgglEvalCoord1d glEvalCoord1d
#define tgglEvalCoord1dv glEvalCoord1dv
#define tgglEvalCoord1f glEvalCoord1f
#define tgglEvalCoord1fv glEvalCoord1fv
#define tgglEvalCoord2d glEvalCoord2d
#define tgglEvalCoord2dv glEvalCoord2dv
#define tgglEvalCoord2f glEvalCoord2f
#define tgglEvalCoord2fv glEvalCoord2fv
#define tgglEvalMesh1 glEvalMesh1
#define tgglEvalMesh2 glEvalMesh2
#define tgglEvalPoint1 glEvalPoint1
#define tgglEvalPoint2 glEvalPoint2
#define tgglFeedbackBuffer glFeedbackBuffer
#define tgglFinish glFinish
#define tgglFlush glFlush
#define tgglFogf glFogf
#define tgglFogfv glFogfv
#define tgglFogi glFogi
#define tgglFogiv glFogiv
#define tgglFrontFace glFrontFace
#define tgglFrustum glFrustum
#define tgglGenLists glGenLists
#define tgglGenTextures glGenTextures
#define tgglGetBooleanv glGetBooleanv
#define tgglGetClipPlane glGetClipPlane
#define tgglGetDoublev glGetDoublev
#define tgglGetError glGetError
#define tgglGetFloatv glGetFloatv
#define tgglGetIntegerv glGetIntegerv
#define tgglGetLightfv glGetLightfv
#define tgglGetLightiv glGetLightiv
#define tgglGetMapdv glGetMapdv
#define tgglGetMapfv glGetMapfv
#define tgglGetMapiv glGetMapiv
#define tgglGetMaterialfv glGetMaterialfv
#define tgglGetMaterialiv glGetMaterialiv
#define tgglGetPixelMapfv glGetPixelMapfv
#define tgglGetPixelMapuiv glGetPixelMapuiv
#define tgglGetPixelMapusv glGetPixelMapusv
#define tgglGetPointerv glGetPointerv
#define tgglGetPolygonStipple glGetPolygonStipple
#define tgglGetString glGetString
#define tgglGetTexEnviv glGetTexEnviv
#define tgglGetTexEnvfv glGetTexEnvfv
#define tgglGetTexGendv glGetTexGendv
#define tgglGetTexGenfv glGetTexGenfv
#define tgglGetTexGeniv glGetTexGeniv
#define tgglGetTexImage glGetTexImage
#define tgglGetTexLevelParameterfv glGetTexLevelParameterfv
#define tgglGetTexLevelParameteriv glGetTexLevelParameteriv
#define tgglGetTexParameterfv glGetTexParameterfv
#define tgglGetTexParameteriv glGetTexParameteriv
#define tgglHint glHint
#define tgglIndexMask glIndexMask
#define tgglIndexPointer glIndexPointer
#define tgglIndexd glIndexd
#define tgglIndexdv glIndexdv
#define tgglIndexf glIndexf
#define tgglIndexfv glIndexfv
#define tgglIndexi glIndexi
#define tgglIndexiv glIndexiv
#define tgglIndexs glIndexs
#define tgglIndexsv glIndexsv
#define tgglIndexub glIndexub
#define tgglIndexubv glIndexubv
#define tgglInitNames glInitNames
#define tgglInterleavedArrays glInterleavedArrays
#define tgglIsEnabled glIsEnabled
#define tgglIsList glIsList
#define tgglIsTexture glIsTexture
#define tgglLightModelf glLightModelf
#define tgglLightModelfv glLightModelfv
#define tgglLightModeli glLightModeli
#define tgglLightModeliv glLightModeliv
#define tgglLightf glLightf
#define tgglLightfv glLightfv
#define tgglLighti glLighti
#define tgglLightiv glLightiv
#define tgglLineStipple glLineStipple
#define tgglLineWidth glLineWidth
#define tgglListBase glListBase
#define tgglLoadIdentity glLoadIdentity
#define tgglLoadMatrixd glLoadMatrixd
#define tgglLoadMatrixf glLoadMatrixf
#define tgglLoadName glLoadName
#define tgglLogicOp glLogicOp
#define tgglMap1d glMap1d
#define tgglMap1f glMap1f
#define tgglMap2d glMap2d
#define tgglMap2f glMap2f
#define tgglMapGrid1d glMapGrid1d
#define tgglMapGrid1f glMapGrid1f
#define tgglMapGrid2d glMapGrid2d
#define tgglMapGrid2f glMapGrid2f
#define tgglMaterialf glMaterialf
#define tgglMaterialfv glMaterialfv
#define tgglMateriali glMateriali
#define tgglMaterialiv glMaterialiv
#define tgglMatrixMode glMatrixMode
#define tgglMultMatrixd glMultMatrixd
#define tgglMultMatrixf glMultMatrixf
#define tgglNewList glNewList
#define tgglNormal3b glNormal3b
#define tgglNormal3bv glNormal3bv
#define tgglNormal3d glNormal3d
#define tgglNormal3dv glNormal3dv
#define tgglNormal3f glNormal3f
#define tgglNormal3fv glNormal3fv
#define tgglNormal3i glNormal3i
#define tgglNormal3iv glNormal3iv
#define tgglNormal3s glNormal3s
#define tgglNormal3sv glNormal3sv
#define tgglNormalPointer glNormalPointer
#define tgglOrtho glOrtho
#define tgglPassThrough glPassThrough
#define tgglPixelMapfv glPixelMapfv
#define tgglPixelMapuiv glPixelMapuiv
#define tgglPixelMapusv glPixelMapusv
#define tgglPixelStoref glPixelStoref
#define tgglPixelStorei glPixelStorei
#define tgglPixelTransferf glPixelTransferf
#define tgglPixelTransferi glPixelTransferi
#define tgglPixelZoom glPixelZoom
#define tgglPointSize glPointSize
#define tgglPolygonMode glPolygonMode
#define tgglPolygonOffset glPolygonOffset
#define tgglPolygonStipple glPolygonStipple
#define tgglPopAttrib glPopAttrib
#define tgglPopClientAttrib glPopClientAttrib
#define tgglPopMatrix glPopMatrix
#define tgglPopName glPopName
#define tgglPrioritizeTextures glPrioritizeTextures
#define tgglPushAttrib glPushAttrib
#define tgglPushClientAttrib glPushClientAttrib
#define tgglPushMatrix glPushMatrix
#define tgglPushName glPushName
#define tgglRasterPos2d glRasterPos2d
#define tgglRasterPos2dv glRasterPos2dv
#define tgglRasterPos2f glRasterPos2f
#define tgglRasterPos2fv glRasterPos2fv
#define tgglRasterPos2i glRasterPos2i
#define tgglRasterPos2iv glRasterPos2iv
#define tgglRasterPos2s glRasterPos2s
#define tgglRasterPos2sv glRasterPos2sv
#define tgglRasterPos3d glRasterPos3d
#define tgglRasterPos3dv glRasterPos3dv
#define tgglRasterPos3f glRasterPos3f
#define tgglRasterPos3fv glRasterPos3fv
#define tgglRasterPos3i glRasterPos3i
#define tgglRasterPos3iv glRasterPos3iv
#define tgglRasterPos3s glRasterPos3s
#define tgglRasterPos3sv glRasterPos3sv
#define tgglRasterPos4d glRasterPos4d
#define tgglRasterPos4dv glRasterPos4dv
#define tgglRasterPos4f glRasterPos4f
#define tgglRasterPos4fv glRasterPos4fv
#define tgglRasterPos4i glRasterPos4i
#define tgglRasterPos4iv glRasterPos4iv
#define tgglRasterPos4s glRasterPos4s
#define tgglRasterPos4sv glRasterPos4sv
#define tgglReadBuffer glReadBuffer
#define tgglReadPixels glReadPixels
#define tgglRectd glRectd
#define tgglRectdv glRectdv
#define tgglRectf glRectf
#define tgglRectfv glRectfv
#define tgglRecti glRecti
#define tgglRectiv glRectiv
#define tgglRects glRects
#define tgglRectsv glRectsv
#define tgglRenderMode glRenderMode
#define tgglRotated glRotated
#define tgglRotatef glRotatef
#define tgglScaled glScaled
#define tgglScalef glScalef
#define tgglScissor glScissor
#define tgglSelectBuffer glSelectBuffer
#define tgglShadeModel glShadeModel
#define tgglStencilFunc glStencilFunc
#define tgglStencilMask glStencilMask
#define tgglStencilOp glStencilOp
#define tgglTexCoord1d glTexCoord1d
#define tgglTexCoord1dv glTexCoord1dv
#define tgglTexCoord1f glTexCoord1f
#define tgglTexCoord1fv glTexCoord1fv
#define tgglTexCoord1i glTexCoord1i
#define tgglTexCoord1iv glTexCoord1iv
#define tgglTexCoord1s glTexCoord1s
#define tgglTexCoord1sv glTexCoord1sv
#define tgglTexCoord2d glTexCoord2d
#define tgglTexCoord2dv glTexCoord2dv
#define tgglTexCoord2f glTexCoord2f
#define tgglTexCoord2fv glTexCoord2fv
#define tgglTexCoord2i glTexCoord2i
#define tgglTexCoord2iv glTexCoord2iv
#define tgglTexCoord2s glTexCoord2s
#define tgglTexCoord2sv glTexCoord2sv
#define tgglTexCoord3d glTexCoord3d
#define tgglTexCoord3dv glTexCoord3dv
#define tgglTexCoord3f glTexCoord3f
#define tgglTexCoord3fv glTexCoord3fv
#define tgglTexCoord3i glTexCoord3i
#define tgglTexCoord3iv glTexCoord3iv
#define tgglTexCoord3s glTexCoord3s
#define tgglTexCoord3sv glTexCoord3sv
#define tgglTexCoord4d glTexCoord4d
#define tgglTexCoord4dv glTexCoord4dv
#define tgglTexCoord4f glTexCoord4f
#define tgglTexCoord4fv glTexCoord4fv
#define tgglTexCoord4i glTexCoord4i
#define tgglTexCoord4iv glTexCoord4iv
#define tgglTexCoord4s glTexCoord4s
#define tgglTexCoord4sv glTexCoord4sv
#define tgglTexCoordPointer glTexCoordPointer
#define	tgglTexEnvf glTexEnvf
#define	tgglTexEnvfv glTexEnvfv
#define	tgglTexEnvi glTexEnvi
#define	tgglTexEnviv glTexEnviv
#define tgglTexGend glTexGend
#define tgglTexGendv glTexGendv
#define tgglTexGenf glTexGenf
#define tgglTexGenfv glTexGenfv
#define tgglTexGeni glTexGeni
#define tgglTexGeniv glTexGeniv
#define tgglTexImage1D glTexImage1D
#define tgglTexImage2D glTexImage2D
#define tgglTexParameterf glTexParameterf
#define tgglTexParameterfv glTexParameterfv
#define tgglTexParameteri glTexParameteri
#define tgglTexParameteriv glTexParameteriv
#define tgglTexSubImage1D glTexSubImage1D
#define tgglTexSubImage2D glTexSubImage2D
#define tgglTranslated glTranslated
#define tgglTranslatef glTranslatef
#define tgglVertex2d glVertex2d
#define tgglVertex2dv glVertex2dv
#define tgglVertex2f glVertex2f
#define tgglVertex2fv glVertex2fv
#define tgglVertex2i glVertex2i
#define tgglVertex2iv glVertex2iv
#define tgglVertex2s glVertex2s
#define tgglVertex2sv glVertex2sv
#define tgglVertex3d glVertex3d
#define tgglVertex3dv glVertex3dv
#define tgglVertex3f glVertex3f
#define tgglVertex3fv glVertex3fv
#define tgglVertex3i glVertex3i
#define tgglVertex3iv glVertex3iv
#define tgglVertex3s glVertex3s
#define tgglVertex3sv glVertex3sv
#define tgglVertex4d glVertex4d
#define tgglVertex4dv glVertex4dv
#define tgglVertex4f glVertex4f
#define tgglVertex4fv glVertex4fv
#define tgglVertex4i glVertex4i
#define tgglVertex4iv glVertex4iv
#define tgglVertex4s glVertex4s
#define tgglVertex4sv glVertex4sv
#define tgglVertexPointer glVertexPointer
#define tgglViewport glViewport

#ifdef GLX_VERSION_1_1 // catch all for any GLX-aware situation
#define tgglXChooseVisual glXChooseVisual
#define tgglXCreateContext glXCreateContext
#define tgglXDestroyContext glXDestroyContext
#define tgglXMakeCurrent glXMakeCurrent
#define tgglXSwapBuffers glXSwapBuffers
#define tgglXGetProcAddressARB glXGetProcAddressARB
#endif
 
#endif
